<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2018 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: liu21st <liu21st@gmail.com>
// +----------------------------------------------------------------------

namespace think\annotation\command\make;

use think\annotation\InteractsWithRoute;
use think\console\command\Make;
use think\console\Input;
use think\console\Output;

class Doc extends Make
{
    use InteractsWithRoute;
    protected $type = "Annotation";

    protected function configure()
    {
        parent::configure();
        $this->setName('annotation:doc')
            ->setDescription('Create a new annotation doc');
    }

    protected function getStub(): string
    {
        return __DIR__ . DIRECTORY_SEPARATOR. 'stubs' . DIRECTORY_SEPARATOR . 'annotation.plain.stub';
    }

    protected function getNamespace(string $app): string
    {
        return parent::getNamespace($app) . '\\annotation';
    }

    protected function execute(Input $input, Output $output)
    {
        return parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
